"""Conflict resolver for temporal conflicts."""

from datetime import datetime
from typing import List
import structlog

from src.models import Fact, ConflictResolution, GraphNode, GraphRelationship
from src.memory_engine.graph_store import GraphStore

logger = structlog.get_logger()


class ConflictResolver:
    """
    Resolve temporal conflicts between facts.
    Implements deterministic conflict resolution logic.
    """

    def __init__(self, graph_store: GraphStore):
        self.graph_store = graph_store

    async def resolve_conflict(
        self,
        new_fact: Fact,
        existing_facts: list[Fact],
    ) -> ConflictResolution:
        """
        Resolve temporal conflicts between facts.

        When a new fact contradicts existing facts:
        1. Set invalid_at on old facts
        2. Create new fact with valid_at
        3. Create SUPERSEDED_BY relationship

        Args:
            new_fact: Incoming fact to store
            existing_facts: Potentially conflicting existing facts

        Returns:
            ConflictResolution with actions to take
        """
        nodes_to_invalidate: list[str] = []
        nodes_to_create: list[GraphNode] = []
        relationships_to_create: list[GraphRelationship] = []

        # Detect conflicts
        conflicting_facts = self._detect_conflicts(new_fact, existing_facts)

        if not conflicting_facts:
            # No conflicts, just create new node
            new_node = GraphNode(
                id="",  # Will be generated by graph_store
                entity_id=new_fact.entity_id,
                entity_type=new_fact.entity_type,
                properties=new_fact.properties,
                valid_at=new_fact.valid_at,
                invalid_at=None,
                tenant_id=new_fact.tenant_id,
                source_observation_id=new_fact.source_observation_id,
            )
            nodes_to_create.append(new_node)

            return ConflictResolution(
                nodes_to_invalidate=[],
                nodes_to_create=nodes_to_create,
                relationships_to_create=[],
                reason="No conflicts detected",
            )

        # Resolve conflicts
        for old_fact in conflicting_facts:
            # Mark old fact as invalid
            nodes_to_invalidate.append(old_fact.id)

            # Create new node
            new_node = GraphNode(
                id="",  # Will be generated
                entity_id=new_fact.entity_id,
                entity_type=new_fact.entity_type,
                properties=new_fact.properties,
                valid_at=new_fact.valid_at,
                invalid_at=None,
                tenant_id=new_fact.tenant_id,
                source_observation_id=new_fact.source_observation_id,
            )
            nodes_to_create.append(new_node)

            # Create SUPERSEDED_BY relationship
            # Note: We'll need to create this after nodes are created
            # Store as placeholder for now
            relationships_to_create.append(
                GraphRelationship(
                    id="",
                    from_node_id=old_fact.id,
                    to_node_id="",  # Will be filled after new node creation
                    relationship_type="SUPERSEDED_BY",
                    properties={
                        "reason": "temporal_conflict",
                        "old_value": old_fact.properties,
                        "new_value": new_fact.properties,
                    },
                    valid_at=new_fact.valid_at,
                    invalid_at=None,
                )
            )

        logger.info(
            "conflict_resolved",
            entity_id=new_fact.entity_id,
            conflicts_count=len(conflicting_facts),
            nodes_to_invalidate=len(nodes_to_invalidate),
            nodes_to_create=len(nodes_to_create),
        )

        return ConflictResolution(
            nodes_to_invalidate=nodes_to_invalidate,
            nodes_to_create=nodes_to_create,
            relationships_to_create=relationships_to_create,
            reason=f"Resolved {len(conflicting_facts)} temporal conflicts",
        )

    def _detect_conflicts(self, new_fact: Fact, existing_facts: list[Fact]) -> list[Fact]:
        """
        Detect which existing facts conflict with the new fact.

        A conflict occurs when:
        - Same entity_id
        - Same property keys with different values
        - Existing fact is still valid (invalid_at is None)

        Args:
            new_fact: New fact to check
            existing_facts: Existing facts to check against

        Returns:
            List of conflicting facts
        """
        conflicts = []

        for existing in existing_facts:
            # Skip if already invalid
            if existing.invalid_at is not None:
                continue

            # Skip if different entity
            if existing.entity_id != new_fact.entity_id:
                continue

            # Check for property conflicts
            has_conflict = False
            for key, new_value in new_fact.properties.items():
                if key in existing.properties:
                    old_value = existing.properties[key]
                    if old_value != new_value:
                        has_conflict = True
                        break

            if has_conflict:
                conflicts.append(existing)

        return conflicts

    async def execute_resolution(
        self,
        resolution: ConflictResolution,
        tenant_id: str,
    ) -> dict:
        """
        Execute the conflict resolution actions.

        Args:
            resolution: ConflictResolution with actions
            tenant_id: Tenant identifier

        Returns:
            Dictionary with created node/relationship IDs
        """
        created_node_ids = []
        created_rel_ids = []

        try:
            # 1. Invalidate old nodes
            for node_id in resolution.nodes_to_invalidate:
                await self.graph_store.invalidate_node(
                    node_id=node_id,
                    invalid_at=datetime.utcnow(),
                    reason="superseded_by_new_fact",
                )

            # 2. Create new nodes
            for node in resolution.nodes_to_create:
                node_id = await self.graph_store.create_node(
                    entity_id=node.entity_id,
                    entity_type=node.entity_type,
                    properties=node.properties,
                    valid_at=node.valid_at,
                    tenant_id=tenant_id,
                    source_observation_id=node.source_observation_id,
                )
                created_node_ids.append(node_id)

            # 3. Create relationships
            for i, rel in enumerate(resolution.relationships_to_create):
                # Use the newly created node ID
                to_node_id = created_node_ids[i] if i < len(created_node_ids) else rel.to_node_id

                rel_id = await self.graph_store.create_relationship(
                    from_node=rel.from_node_id,
                    to_node=to_node_id,
                    relationship_type=rel.relationship_type,
                    properties=rel.properties,
                    valid_at=rel.valid_at,
                )
                created_rel_ids.append(rel_id)

            logger.info(
                "conflict_resolution_executed",
                nodes_invalidated=len(resolution.nodes_to_invalidate),
                nodes_created=len(created_node_ids),
                relationships_created=len(created_rel_ids),
            )

            return {
                "node_ids": created_node_ids,
                "relationship_ids": created_rel_ids,
            }

        except Exception as e:
            logger.error(
                "conflict_resolution_execution_failed",
                error=str(e),
            )
            raise
